---
# tasks file for mysql
- name: Install MYSQL server
  shell: apt-get -y install mysql-server

- name: Install MYSQL client
  shell: apt-get -y install mysql-client

- name: Install the MYSQL service
  shell: service mysql start